#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_FILE="${ROOT_DIR}/deploy/env/.env.prod"

if [[ -f "${OUT_FILE}" && "${FORCE_RENDER_ENV:-0}" != "1" ]]; then
  echo "${OUT_FILE} already exists. Set FORCE_RENDER_ENV=1 to overwrite."
  exit 0
fi

DRAFTED_DOMAIN="${DRAFTED_DOMAIN:-example.com}"
POSTGRES_DB="${POSTGRES_DB:-drafted}"
POSTGRES_USER="${POSTGRES_USER:-drafted}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-drafted_change_me}"
JWT_SECRET="${JWT_SECRET:-CHANGE_ME_WITH_32_PLUS_CHAR_SECRET}"
GEMINI_API_KEY="${GEMINI_API_KEY:-REPLACE_WITH_REAL_GEMINI_KEY}"

cat >"${OUT_FILE}" <<EOF
APP_ENV=production
DRAFTED_DOMAIN=${DRAFTED_DOMAIN}
API_BASE_URL=https://${DRAFTED_DOMAIN}
WEB_BASE_URL=https://${DRAFTED_DOMAIN}
CORS_ORIGINS=https://${DRAFTED_DOMAIN}

JWT_SECRET=${JWT_SECRET}
JWT_ISSUER=drafted-mvp
JWT_TTL_SECONDS=604800

VAR_DIR=/app/var
RUN_INPROCESS_WORKER=false
WORKER_POLL_INTERVAL_SECONDS=1.0
WORKER_HEARTBEAT_TTL_SECONDS=120

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
REDIS_URL=redis://redis:6379/0

GEMINI_API_KEY=${GEMINI_API_KEY}
GEMINI_BASE_URL=https://generativelanguage.googleapis.com/v1beta
GEMINI_TEXT_MODEL=gemini-2.5-flash
GEMINI_IMAGE_MODEL_PREVIEW=gemini-3-pro-image-preview
GEMINI_IMAGE_MODEL_FINAL=gemini-3-pro-image-preview

JOB_MAX_RETRIES=2
IDEMPOTENCY_WINDOW_SECONDS=86400
EOF

echo "Wrote ${OUT_FILE}"
